### PR TITLE
Patch and tests

### LINKED ISSUE #30: Outdated `schema_url` parameter default
**Describe the bug**
Default points to wrong canonical source. Should be `https://raw.githubusercontent.com/nf-osi/nf-metadata-dictionary/main/NF.jsonld`
https://github.com/nf-osi/nfportalutils/blob/5907ccb1495ed0572b7299251b1fe525223bf8a4/R/assign_study_data_types.R#L75

**Additional context**
Until fixed, correct url should be passed in, and this might affect results in usages such as: https://github.com/nf-osi/nfportalutils/blob/5907ccb1495ed0572b7299251b1fe525223bf8a4/example_script/update_portal_values.R#L35-L44

### LINKED ISSUE #33: new_project function overwrites existing wiki
**Describe the bug**
`new_project` overwrites existing project wiki, if a project with the same name exists and you have write access. 
It does throw an error but it's a bit confusing:  `Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: raise_anno_type_error() missing 1 required positional argument: 'anno_type' ` and it still overwrites the project wiki. 

**To Reproduce**
Create a project with `new_project`
Run the same function again. 

**Expected behavior**
Function to create new project should detect if project name already exists and ask if you want to overwrite

**Screenshots**
After 3-4 runs without realizing what i was doing... :)
Screen Shot 2022-02-17 at 6 11 15 PM

**Additional context**
This is not a big deal for this particular project but could be an issue if two different projects had the same name. I forgot that I had already created a project for this person while we were waiting for a DSP, etc.

### LINKED ISSUE #34: Default project fileview schema should accomodate data schema for `species` better
**Description**
The original script instantiating the default project fileview limits the species field to 15 characters.
https://github.com/nf-osi/nfportalutils/blob/develop/R/new_project.R#L99

It's going to be easy for someone to use a valid value for species in the future that exceed that limit and break things; see current valid values for species: https://github.com/nf-osi/nf-metadata-dictionary/blob/main/NF.csv#L202. This is not a bug yet because "Oryctolagus cuniculus" is not common now, but those scientific names for species in general can get pretty long...

### PR DESCRIPTION
**Pull request by anngvu**

### CODE REVIEW

File: R/new_project.R [hunk 1]
```diff
@@ -83,52 +83,86 @@ new_project <- function(name,
...
+    project <- synapseclient$Project(project_name)
+    project <- .syn$store(project, createOrUpdate = FALSE)
+    project
+  }
+}
+
+#' Create default project fileview
+#' 
+#' @param project A project entity.
+add_default_fileview <- function(project) {
```
Comment (allaway) [inline R/new_project.R:121]: This is a fine way of doing this for now. I'm wondering if we should do this differently in the future. Since our (nf.jsonld) schema is dynamic, I wonder if we could have a, say, weekly job that does the following: 

- check for changes to jsonld schema since last run, if no changes, stop
- if changes, iterate over each project view schema:
- for each view, first run `syn._get_annotation_view_columns()` to get all annotations on files within scope of view
- then, for all annotation keys that are defined `parents` in the jsonld schema: 
- Set as STRINGLIST if lists are permitted in jsonld schema. 
- Set as other column types as necessary (maybe we need to define these in the jsonld?) 
- modify the maximumSize to the max length valid value if a string/stringlist. 
- set as max length, say, 50, if string type but valid values are not restricted. 
- for all columns not in the jsonld schema, include them in the view unchanged (ie use the schema that `syn._get_annotation_view_columns()`  returns)
- if total number columns >152, skip (and send log via email?) 
- repeat on all NF Portal study views

What do you think?

**Review by allaway — APPROVED** [review]
Looks good to me! Works great in a quick test.

File: R/new_project.R (hunk 1 above)
Comment (anngvu) [reply R/new_project.R:121]: I'll add it as a suggestion in https://github.com/nf-osi/jobs. It would help with the occasional project fileview being unable to be accessed.

> Set as other column types as necessary (maybe we need to define these in the jsonld?)

That would be another issue for https://github.com/nf-osi/nf-metadata-dictionary. The Validation Rules field can get more usage, though would have to translate the Schematic specification "int" to mean the Synapse INTEGER, etc. If you wanted to use an additional column to specify the Synapse type directly, it wouldn't get translated to the jsonld.

> set as max length, say, 50, if string type but valid values are not restricted. 

I think there must a reason why specimenID was originally set to a limit of 300 (someone used a really long ID somewhere?)... It would help when the validation for string includes string length. As of this writing, SchemaHub says it's a future feature.

Comment (allaway) [reply R/new_project.R:121]: > I think there must a reason why specimenID was originally set to a limit of 300 (someone used a really long ID somewhere?)... It would help when the validation for string includes string length. As of this writing, SchemaHub says it's a future feature.

My _guess_ is that the length is an artifact of pre-STRINGLIST days on synapse, and it was a long comma separated string of many values, but just a guess!
